window.PRODUCTS = [
  // PIZZA
  { id: 'pizza-original', name: 'Original Pizza', nameAr: 'بيتزا عادي', category: 'pizza', sku: '2007166600721', image: 'Products/01. PIZZA/Pizza Original.webp', description: 'A classic baked pizza snack with a perfectly golden crust.', descriptionAr: 'وجبة بيتزا مخبوزة كلاسيكية بعجينة ذهبية مثالية.' },
  { id: 'pizza-spicy', name: 'Spicy Pizza', nameAr: 'بيتزا حارة', category: 'pizza', sku: '2007166600738', image: 'Products/01. PIZZA/Pizza Spicy.webp', description: 'A spicy variant of our classic pizza snack with bold flavors.', descriptionAr: 'نسخة حارة من وجبة البيتزا الكلاسيكية بنكهات جريئة.' },

  // FATAYER
  { id: 'fatayer-cheese', name: 'Cheese Fatayer', nameAr: 'فطيرة جبن', category: 'fatayer', sku: '2007166600691', image: 'Products/02. FATAYER/Fatayer Cheese.webp', description: 'Soft fatayer filled with rich, creamy cheese.', descriptionAr: 'فطيرة طرية محشوة بالجبن الكريمي.' },
  { id: 'fatayer-zaatar', name: 'Zaatar Fatayer', nameAr: 'فطيرة زعتر', category: 'fatayer', sku: '2007166600707', image: 'Products/02. FATAYER/Fatayer Zaatar.webp', description: 'Traditional fatayer filled with fragrant zaatar blend.', descriptionAr: 'فطيرة تقليدية محشوة بخليط الزعتر العطر.' },
  { id: 'fatayer-cheese-zaatar', name: 'Cheese & Zaatar Fatayer', nameAr: 'فطيرة جبن وزعتر', category: 'fatayer', sku: '2007166600714', image: 'Products/02. FATAYER/Fatayer Cheese & Zaatar.webp', description: 'The best of both worlds — cheese and zaatar in every bite.', descriptionAr: 'الجمع المثالي بين الجبن والزعتر في كل لقمة.' },

  // CROISSANT - Single
  { id: 'croissant-cheese', name: 'Cheese Croissant', nameAr: 'كرواسان جبن', category: 'croissant', sku: '2001176070307', image: 'Products/03. CROISSANT/Croissant single/Cheese - Croissant.webp', description: 'Buttery croissant filled with creamy cheese.', descriptionAr: 'كرواسان زبدي محشو بالجبن الكريمي.' },
  { id: 'croissant-chocolate', name: 'Chocolate Croissant', nameAr: 'كرواسان شوكولات', category: 'croissant', sku: '2001176070314', weight: '60g', image: 'Products/03. CROISSANT/Croissant single/Chocolate - Croissant.webp', description: 'Enjoy the rich taste of Alfaysal Chocolate Croissant, a soft and flaky pastry filled with smooth chocolate cream. Crafted to deliver a warm, indulgent experience, it is perfect for a quick snack or a sweet moment anytime during the day. Simply heat and enjoy its freshly baked taste in minutes.', descriptionAr: 'استمتع بالطعم الغني لكرواسان الشوكولاتة من الفيصل، معجنات طرية وهشة محشوة بكريمة الشوكولاتة الناعمة. مصنوع لتقديم تجربة دافئة ومدللة، مثالي لوجبة خفيفة سريعة أو لحظة حلوة في أي وقت خلال اليوم.', bullets: ['Light, flaky croissant pastry with a rich chocolate filling', 'Soft and indulgent texture with a golden baked finish', 'Perfect for quick snacking or on-the-go enjoyment', 'Ready to heat for a warm, bakery-fresh experience', 'Ideal for breakfast, breaks, or sweet cravings'] },
  { id: 'croissant-oregano', name: 'Oregano Croissant', nameAr: 'كرواسان زعتر', category: 'croissant', sku: '2001176070321', image: 'Products/03. CROISSANT/Croissant single/Oregano - Croissant.webp', description: 'Savory croissant with aromatic oregano topping.', descriptionAr: 'كرواسان لذيذ مع طبقة زعتر عطري.' },
  { id: 'croissant-plain', name: 'Plain Croissant', nameAr: 'كرواسان سادة', category: 'croissant', sku: '2001176070338', image: 'Products/03. CROISSANT/Croissant single/Plain - Croissant.webp', description: 'Classic buttery croissant, perfectly golden and flaky.', descriptionAr: 'كرواسان زبدي كلاسيكي، ذهبي وهش تماماً.' },
  { id: 'croissant-strawberry', name: 'Strawberry Croissant', nameAr: 'كرواسان فراولة', category: 'croissant', sku: '2001176070352', image: 'Products/03. CROISSANT/Croissant single/Strawberry - Croissant.webp', description: 'Light croissant filled with sweet strawberry cream.', descriptionAr: 'كرواسان خفيف محشو بكريمة الفراولة الحلوة.' },
  { id: 'croissant-honey', name: 'Honey Croissant', nameAr: 'كرواسان عسل', category: 'croissant', sku: '2001176070354', image: 'Products/03. CROISSANT/Croissant single/Honey - Croissant.webp', description: 'Delicate croissant drizzled with natural honey.', descriptionAr: 'كرواسان رقيق مرشوش بالعسل الطبيعي.' },
  { id: 'croissant-cheese-oregano', name: 'Cheese & Oregano Croissant', nameAr: 'كرواسان جبن وزعتر', category: 'croissant', sku: 'CHSORG001', image: 'Products/03. CROISSANT/Croissant single/Cheese and Oregano - Croissant.webp', description: 'A savory combination of cheese and oregano in a flaky croissant.', descriptionAr: 'توليفة لذيذة من الجبن والزعتر في كرواسان هش.' },

  // CROISSANT - Family
  { id: 'family-croissant-cheese', name: 'Cheese Family Croissant', nameAr: 'كرواسان عائلي جبن', category: 'croissant', sku: '2002283101526', image: 'Products/03. CROISSANT/FAMILY/FAMILY CROISSANT CHEESE.webp', description: 'Family-sized pack of cheese croissants for sharing.', descriptionAr: 'عبوة عائلية من كرواسان الجبن للمشاركة.' },
  { id: 'family-croissant-zaatar', name: 'Zaatar Family Croissant', nameAr: 'كرواسان عائلي زعتر', category: 'croissant', sku: '2002283102523', image: 'Products/03. CROISSANT/FAMILY/FAMILY CROISSANT ZAATAR.webp', description: 'Family-sized pack of zaatar croissants.', descriptionAr: 'عبوة عائلية من كرواسان الزعتر.' },
  { id: 'family-croissant-plain', name: 'Plain Family Croissant', nameAr: 'كرواسان عائلي سادة', category: 'croissant', sku: '2002283103520', image: 'Products/03. CROISSANT/FAMILY/FAMILY CROISSANT PLAIN.webp', description: 'Family-sized pack of classic plain croissants.', descriptionAr: 'عبوة عائلية من كرواسان سادة كلاسيكية.' },
  { id: 'family-croissant-honey', name: 'Honey Family Croissant', nameAr: 'كرواسان عائلي عسل', category: 'croissant', sku: '2002283104527', image: 'Products/03. CROISSANT/FAMILY/FAMILY croissant honey.webp', description: 'Family-sized pack of honey croissants.', descriptionAr: 'عبوة عائلية من كرواسان العسل.' },
  { id: 'family-croissant-strawberry', name: 'Strawberry Family Croissant', nameAr: 'كرواسان عائلي فراولة', category: 'croissant', sku: '2002283105524', image: 'Products/03. CROISSANT/FAMILY/FAMILY croissant strawberry.webp', description: 'Family-sized pack of strawberry croissants.', descriptionAr: 'عبوة عائلية من كرواسان الفراولة.' },
  { id: 'family-croissant-chocolate', name: 'Chocolate Family Croissant', nameAr: 'كرواسان عائلي شوكولات', category: 'croissant', sku: '2002283106521', image: 'Products/03. CROISSANT/FAMILY/FAMILY CROISSANT CHOCOLATE.webp', description: 'Family-sized pack of chocolate croissants.', descriptionAr: 'عبوة عائلية من كرواسان الشوكولات.' },

  // CROISSANT - Sesame Single
  { id: 'sesame-croissant-plain', name: 'Plain Sesame Croissant', nameAr: 'كرواسان سمسم سادة', category: 'croissant', sku: '2007166600462', image: 'Products/03. CROISSANT/SESAME SINGLE/Sesame Croissan Plain.webp', description: 'Classic croissant topped with sesame seeds.', descriptionAr: 'كرواسان كلاسيكي مغطى ببذور السمسم.' },
  { id: 'sesame-croissant-cheese', name: 'Cheese Sesame Croissant', nameAr: 'كرواسان سمسم بالجبن', category: 'croissant', sku: '2007166600479', image: 'Products/03. CROISSANT/SESAME SINGLE/Sesame Croissant Cheese.webp', description: 'Sesame-topped croissant with a cheesy filling.', descriptionAr: 'كرواسان بالسمسم محشو بالجبن.' },

  // CUPCAKE - Outer
  { id: 'cupcake-strawberry-cream', name: 'Strawberry Cream Cupcake', nameAr: 'كب كيك كريمة فراولة', category: 'cupcake', sku: '2007166600073', image: 'Products/04. CUPCAKE/CupCAKES/CUPCAKE STRAWBERRY 60G 2PC.webp', description: 'Soft cupcake filled with smooth strawberry cream.', descriptionAr: 'كب كيك طري محشو بكريمة الفراولة الناعمة.' },
  { id: 'cupcake-vanilla', name: 'Vanilla Cupcake', nameAr: 'كب كيك فانيليا', category: 'cupcake', sku: '2001176070185', image: 'Products/04. CUPCAKE/CupCAKES/CUPCAKE VANILLA 60G 2PC.webp', description: 'A classic vanilla cupcake, soft and delicious.', descriptionAr: 'كب كيك فانيليا كلاسيكي، طري ولذيذ.' },
  { id: 'cupcake-choco-cream', name: 'Choco Cream Cupcake', nameAr: 'كب كيك كريمة شوكولات', category: 'cupcake', sku: '2007166600134', image: 'Products/04. CUPCAKE/CupCAKES/CUPCAKE CHOCO CREAM 60G 2PC.webp', description: 'Cupcake filled with rich chocolate cream.', descriptionAr: 'كب كيك محشو بكريمة شوكولاتة غنية.' },
  { id: 'layered-barcake-choco', name: 'Chocolate Layered Barcake', nameAr: 'كيك طبقي شوكولات', category: 'cupcake', sku: '6275000640134', image: 'Products/04. CUPCAKE/CupCAKES/LAYERED BARCAKE CHOCOLATE CREAM 25G.webp', description: 'Layered bar cake with a chocolate cream filling.', descriptionAr: 'كيك طبقي بحشوة كريمة الشوكولات.' },
  { id: 'layered-barcake-vanilla', name: 'Vanilla Layered Barcake', nameAr: 'كيك طبقي فانيليا', category: 'cupcake', sku: '6275000640141', image: 'Products/04. CUPCAKE/CupCAKES/LAYERED BARCAKE VANILLA CREAM 25G.webp', description: 'Layered bar cake with a smooth vanilla cream filling.', descriptionAr: 'كيك طبقي بحشوة كريمة الفانيليا الناعمة.' },
  { id: 'coated-layer-cake-choco', name: 'Chocolate Coated Layer Cake', nameAr: 'كيك طبقي مغطى بالشوكولات', category: 'cupcake', sku: '6275000640165', image: 'Products/04. CUPCAKE/CupCAKES/COATED LAYERED CHOCO CAKE FILLED CHOCO CREAM 35G.webp', description: 'Chocolate-coated layered cake with a creamy center.', descriptionAr: 'كيك طبقي مغطى بالشوكولاتة بمركز كريمي.' },
  { id: 'coated-layer-cake-vanilla', name: 'Vanilla Coated Layer Cake', nameAr: 'كيك طبقي مغطى بالفانيليا', category: 'cupcake', sku: '6275000640172', image: 'Products/04. CUPCAKE/CupCAKES/COATED LAYERED CHOCO CAKE FILLED VANILLA CREAM 35G.webp', description: 'Chocolate-coated layered cake filled with vanilla cream.', descriptionAr: 'كيك طبقي مغطى محشو بكريمة الفانيليا.' },
  { id: 'golden-cake-vanilla', name: 'Vanilla Cream Golden Cake', nameAr: 'كيك ذهبي كريمة فانيليا', category: 'cupcake', sku: '6275000640189', image: 'Products/04. CUPCAKE/CupCAKES/GOLDEN CAKE CAKE FILLED WITH VANILLA CREAM 32G.webp', description: 'Golden sponge cake filled with vanilla cream.', descriptionAr: 'كيك إسفنجي ذهبي محشو بكريمة الفانيليا.' },
  { id: 'golden-cake-choc', name: 'Chocolate Cream Golden Cake', nameAr: 'كيك ذهبي كريمة شوكولات', category: 'cupcake', sku: '6275000640196', image: 'Products/04. CUPCAKE/CupCAKES/GOLDEN CAKE FILLED WITH CHOCOLATE CREAM 32G.webp', description: 'Golden sponge cake filled with chocolate cream.', descriptionAr: 'كيك إسفنجي ذهبي محشو بكريمة الشوكولات.' },
  { id: 'dabdoob-cake', name: 'Dabdoob Cake', nameAr: 'كيك دبدوب', category: 'cupcake', sku: '6275000640202', image: 'Products/04. CUPCAKE/CupCAKES/Dabdoob 30G.webp', description: 'Our beloved Dabdoob — a soft, indulgent treat.', descriptionAr: 'دبدوبنا المحبوب — حلوى طرية ومدللة.' },
  { id: 'cupcake-vanilla-cream', name: 'Vanilla Cream Cupcake', nameAr: 'كب كيك كريمة فانيليا', category: 'cupcake', sku: '6275000640219', image: 'Products/04. CUPCAKE/CupCAKES/CUPCAKE VANILLA FILLED CREAM 60G 2PC.webp', description: 'Soft cupcake filled with smooth vanilla cream.', descriptionAr: 'كب كيك طري محشو بكريمة الفانيليا الناعمة.' },

  // CUPCAKE - Slice Cakes
  { id: 'plain-slice-cake', name: 'Plain Slice Cake', nameAr: 'كيك شريحة سادة', category: 'cupcake', sku: '2001176070611', image: 'Products/04. CUPCAKE/SLICE CAKES/PLAIN SLICE CAKE.webp', description: 'A classic plain slice cake, soft and moist.', descriptionAr: 'كيك شريحة سادة كلاسيكية، طرية ورطبة.' },
  { id: 'cardamom-cake', name: 'Cardamom Cake', nameAr: 'كيك هيل', category: 'cupcake', sku: '2001176070628', image: 'Products/04. CUPCAKE/SLICE CAKES/CARDAMOM CAKE.webp', description: 'Fragrant cake infused with aromatic cardamom.', descriptionAr: 'كيك عطري منكه بالهيل العطر.' },
  { id: 'choco-vanilla-slice', name: 'Choco Vanilla Slice Cake', nameAr: 'كيك شريحة شوكولات فانيليا', category: 'cupcake', sku: '2007166600516', image: 'Products/04. CUPCAKE/SLICE CAKES/CHOCO VANILLA.webp', description: 'Swirled chocolate and vanilla cake layers.', descriptionAr: 'طبقات كيك شوكولاتة وفانيليا ملتوية.' },
  { id: 'vanilla-choco-slice', name: 'Vanilla Chocolate Slice Cake', nameAr: 'كيك شريحة فانيليا شوكولات', category: 'cupcake', sku: '2007166600523', image: 'Products/04. CUPCAKE/SLICE CAKES/vanilla chocolate.webp', description: 'A perfect balance of vanilla and chocolate in every slice.', descriptionAr: 'توازن مثالي بين الفانيليا والشوكولات في كل شريحة.' },

  // TASBEERA
  { id: 'mazmaza-tasbeerah-cheese-zaatar', name: 'Cheese & Zaatar Mazmaza Tasbeerah', nameAr: 'مزمزة تسبيرة جبن وزعتر', category: 'tasbeera', sku: '2001176070864', image: 'Products/06. TASBEERA/Mazmaza Tasbeerah Cheese Zaatar.webp', description: 'Crispy tasbeerah with a cheese and zaatar topping.', descriptionAr: 'تسبيرة مقرمشة مع طبقة جبن وزعتر.' },
  { id: 'mazmaza-tasbeerah-cheese', name: 'Cheese Mazmaza Tasbeerah', nameAr: 'مزمزة تسبيرة جبن', category: 'tasbeera', sku: '2001176070895', image: 'Products/06. TASBEERA/Mazmaza Tasbeerah Cheese.webp', description: 'Crispy tasbeerah with a cheese topping.', descriptionAr: 'تسبيرة مقرمشة مع طبقة جبن.' },
  { id: 'tasbeera-family-cheese', name: 'Cheese Tasbeera Family', nameAr: 'تسبيرة عائلية جبن', category: 'tasbeera', sku: '6275000640257', image: 'Products/06. TASBEERA/TASBEERA FAMILY 4PCS - CHEESE.webp', description: 'Family pack of 4 cheese tasbeera snacks.', descriptionAr: 'عبوة عائلية من 4 قطع تسبيرة بالجبن.' },
  { id: 'tasbeera-family-cheese-zaatar', name: 'Cheese & Zaatar Tasbeera Family', nameAr: 'تسبيرة عائلية جبن وزعتر', category: 'tasbeera', sku: '6275000640264', image: 'Products/06. TASBEERA/TASBEERA FAMILY 4PCS  - CHEESE & ZAATAR.webp', description: 'Family pack of 4 cheese and zaatar tasbeera snacks.', descriptionAr: 'عبوة عائلية من 4 قطع تسبيرة بالجبن والزعتر.' }
];

// Category metadata
window.CATEGORIES = [
  { id: 'pizza',     label: 'Pizza',     labelAr: 'بيتزا',      image: 'Products/01. PIZZA/Pizza Original.webp' },
  { id: 'fatayer',   label: 'Fatayer',   labelAr: 'فطائر',    image: 'Products/02. FATAYER/Fatayer Cheese & Zaatar.webp' },
  { id: 'croissant', label: 'Croissant', labelAr: 'كرواسان',  image: 'Products/03. CROISSANT/FAMILY/FAMILY CROISSANT PLAIN.webp' },
  { id: 'cupcake',   label: 'Cupcake',   labelAr: 'كب كيك',    image: 'Products/04. CUPCAKE/CupCAKES/Dabdoob 30G.webp' },
  { id: 'tasbeera',  label: 'Tasbeera',  labelAr: 'تسبيرة',   image: 'Products/06. TASBEERA/TASBEERA FAMILY 4PCS - CHEESE.webp' }
];
